CREATE TABLE books(
	id VARCHAR(255) PRIMARY KEY,
	name VARCHAR(255),
	pages INT,
     PRICE VARCHAR(150),
     PUBLISHER VARCHAR(256),
     ISSOFTCOPY BOOLEAN,
     EDITION VARCHAR(256),
     BOOKOPENDATE DATE);

CREATE TABLE authors(
	id INT PRIMARY KEY,
	name VARCHAR(255),
	age INT,
	book_id VARCHAR(255) UNIQUE NOT NULL,
	
	CONSTRAINT book_author_fk FOREIGN KEY(book_id) REFERENCES books(id)
);
	